 main: com.enteente.plottools.Plottools
 name: plottools
 version: 1.0
 author: schubc
 description: Change borders of plotsquared plots
 depend: [Vault, PlotSquared]
 commands:
     plottools:
        description: plot tools
        usage: /plottools <info|buy|flags>
        aliases: [ptools]
        permission: plots.use 	
        permission-message: You need basic plotborder permissions to use plottools
